# Generated by Django 4.0.3 on 2022-05-04 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('weight', models.TextField(max_length=255)),
                ('details', models.TextField(max_length=5000)),
                ('publicationYear', models.IntegerField()),
                ('author', models.TextField(max_length=255)),
                ('publisher', models.TextField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('weight', models.TextField(max_length=255)),
                ('details', models.TextField(max_length=5000)),
                ('sex', models.TextField(max_length=10)),
                ('designer', models.TextField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('weight', models.TextField(max_length=255)),
                ('details', models.TextField(max_length=5000)),
                ('manufacture', models.TextField(max_length=255)),
                ('lifespan', models.TextField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('weight', models.TextField(max_length=255)),
                ('details', models.TextField(max_length=5000)),
                ('ram', models.TextField(max_length=10)),
                ('cpu', models.TextField(max_length=100)),
                ('type', models.TextField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(max_length=10000)),
                ('description', models.TextField(max_length=10000)),
                ('price', models.FloatField()),
                ('title', models.TextField(default='', max_length=200)),
                ('detail', models.TextField(default='', max_length=100)),
                ('book', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.book')),
                ('clothes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.clothes')),
                ('electronic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.electronic')),
                ('laptop', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.laptop')),
            ],
        ),
    ]
