# Generated by Django 4.0.2 on 2022-04-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='title',
            field=models.TextField(default='', max_length=200),
        ),
    ]
